version: '2'
services:
  artifactory:
    image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:latest
    network_mode: bridge
    ports:
    - "8081:8081"
    volumes:
    - artifactory_backup:/var/opt/jfrog/artifactory/backup
    - artifactory_data:/var/opt/jfrog/artifactory/data
    - artifactory_etc:/var/opt/jfrog/artifactory/etc
    - artifactory_logs:/var/opt/jfrog/artifactory/logs

  gitlab:
    image: gitlab/gitlab-ce:latest
    network_mode: bridge
    ports:
    - "2222:22"
    - "80:80"
    - "443:443"
    volumes:
    - gitlab_etc:/etc/gitlab
    - gitlab_log:/var/log/gitlab
    - gitlab_opt:/var/opt/gitlab

  jenkins:
    build:
      context: ./jenkins
    image: yja-jenkins
    network_mode: bridge
    ports:
    - "8080:8080"
    - "50000:50000"
    volumes:
    - jenkins_home:/var/jenkins_home

  jira:
    image: cptactionhank/atlassian-jira:latest
    network_mode: bridge
    ports:
    - "8082:8080"
    volumes:
    - jira_var:/var/atlassian/jira

volumes:
  artifactory_backup: {}
  artifactory_data: {}
  artifactory_etc: {}
  artifactory_logs: {}
  gitlab_etc: {}
  gitlab_log: {}
  gitlab_opt: {}
  jenkins_home: {}
  jira_var: {}

networks:
  default:
    external:
      name: bridge
